Repository ConservationInternational/cplus-plugin, pull requests merged in 2024-05, with the labels that each got.

#394 Report Template Updates
  src/cplus_plugin/data/reports/main.qpt
  src/cplus_plugin/definitions/defaults.py
  src/cplus_plugin/gui/qgis_cplus_main.py
  src/cplus_plugin/lib/reports/generator.py
  src/cplus_plugin/lib/reports/manager.py
  src/cplus_plugin/lib/reports/variables.py
  src/cplus_plugin/ui/report_settings.ui
Labels: enhancement

#381 Documentation new features
  docs/user/manual/img/setting-1.png
  docs/user/manual/img/setting-2.png
  docs/user/manual/img/setting-3.png
  docs/user/manual/img/setting-4.png
  docs/user/manual/img/setting-5.png
  docs/user/manual/img/setting-6.png
  docs/user/manual/settings.md
Labels: documentation, Size: 8

#420 Documentation validation masking
  docs/user/manual/img/manual-step3-validation-1.png
  docs/user/manual/img/manual-step3-validation-2.png
  docs/user/manual/img/manual-step3-validation-3.png
  docs/user/manual/img/manual-step3-validation-4.png
  docs/user/manual/img/manual-step3-validation-5.png
  docs/user/manual/img/manual-step3-validation-6.png
  docs/user/manual/img/setting-3.png
  docs/user/manual/img/setting-7.png
  docs/user/manual/img/setting-8.png
  docs/user/manual/img/setting-9.png
  docs/user/manual/settings.md
  docs/user/manual/step-2.md
Labels: documentation, Size: 5

#409 Document step4 logs
  docs/user/manual/img/logs-1.png
  docs/user/manual/img/logs-2.png
  docs/user/manual/img/logs-3.png
  docs/user/manual/img/step-4-1.png
  docs/user/manual/img/step-4-2.png
  docs/user/manual/img/step-4-3.png
  docs/user/manual/img/step-4-4.png
  docs/user/manual/img/step-4.png
  docs/user/manual/index.md
  docs/user/manual/logs.md
  docs/user/manual/step-4.md
  mkdocs.yml
Labels: documentation

#440 Update the logs doc
  docs/user/guide/img/logs-1.png
  docs/user/guide/img/logs-2.png
  docs/user/guide/img/logs-3.png
  docs/user/guide/img/logs-4.png
  docs/user/guide/img/logs-5.png
  docs/user/guide/logs.md
  docs/user/manual/img/logs-1.png
  docs/user/manual/img/logs-2.png
  docs/user/manual/img/logs-3.png
  docs/user/manual/img/logs-4.png
  docs/user/manual/img/scenario-file-1.png
  docs/user/manual/img/scenario-file-2.png
  docs/user/manual/index.md
  docs/user/manual/logs.md
  docs/user/manual/scenario-file.md
  mkdocs.yml
Labels: documentation, Size: 5
