Repository ConservationInternational/cplus-plugin, pull requests merged in 2024-06, with the labels that each got.

#448 Financial NPV PWL
  docs/developer/api/core/api_financials.md
  docs/developer/api/gui/api_npv_financial_model.md
  docs/developer/api/gui/api_npv_manager_dialog.md
  docs/developer/api/gui/api_npv_progress_dialog.md
  docs/developer/api/models/api_financials.md
  mkdocs.yml
  src/cplus_plugin/conf.py
  src/cplus_plugin/definitions/constants.py
  src/cplus_plugin/gui/component_item_model.py
  src/cplus_plugin/gui/financials/__init__.py
  src/cplus_plugin/gui/financials/npv_financial_model.py
  src/cplus_plugin/gui/financials/npv_manager_dialog.py
  src/cplus_plugin/gui/financials/npv_progress_dialog.py
  src/cplus_plugin/gui/model_component_widget.py
  src/cplus_plugin/gui/priority_layer_dialog.py
  src/cplus_plugin/gui/qgis_cplus_main.py
  src/cplus_plugin/icons/mActionNewMap.svg
  src/cplus_plugin/lib/financials.py
  src/cplus_plugin/models/base.py
  src/cplus_plugin/models/financial.py
  src/cplus_plugin/models/helpers.py
  src/cplus_plugin/models/validation.py
  src/cplus_plugin/ui/financial_pwl_dialog.ui
  src/cplus_plugin/ui/qgis_cplus_main_dockwidget.ui
  src/cplus_plugin/utils.py
  test/model_data_for_testing.py
  test/test_financials.py
Labels: enhancement

#477 Added documentation for the NPV
  docs/user/manual/img/mActionNewMap.svg
  docs/user/manual/img/manual-step3.png
  docs/user/manual/img/step3-1.png
  docs/user/manual/img/step3-2.png
  docs/user/manual/img/step3-3.png
  docs/user/manual/img/step3-4.png
  docs/user/manual/img/step3-5.png
  docs/user/manual/img/step3-6.png
  docs/user/manual/img/step3-7.png
  docs/user/manual/step-3.md
Labels: documentation, Size: 5

#487 Update user guide
  docs/user/guide/img/logs-1.png
  docs/user/guide/img/mActionNewMap.svg
  docs/user/guide/img/plugin-step1.png
  docs/user/guide/img/plugin-step2-buttons.png
  docs/user/guide/img/plugin-step2-pathways-buttons.png
  docs/user/guide/img/plugin-step2.png
  docs/user/guide/img/plugin-step3_10.png
  docs/user/guide/img/plugin-step3_2.png
  docs/user/guide/img/plugin-step3_4.png
  docs/user/guide/img/plugin-step3_5.png
  docs/user/guide/img/plugin-step3_6.png
  docs/user/guide/img/plugin-step3_7.png
  docs/user/guide/img/plugin-step3_8.png
  docs/user/guide/img/plugin-step3_9.png
  docs/user/guide/img/plugin-toolbar-icon.png
  docs/user/guide/img/settings-1.png
  docs/user/guide/img/settings-10.png
  docs/user/guide/img/settings-11.png
  docs/user/guide/img/settings-12.png
  docs/user/guide/img/settings-13.png
  docs/user/guide/img/settings-14.png
  docs/user/guide/img/settings-15.png
  docs/user/guide/img/settings-16.png
  docs/user/guide/img/settings-17.png
  docs/user/guide/img/settings-18.png
  docs/user/guide/img/settings-19.png
  docs/user/guide/img/settings-2.png
  docs/user/guide/img/settings-3.png
  docs/user/guide/img/settings-4.png
  docs/user/guide/img/settings-5.png
  docs/user/guide/img/settings-6.png
  docs/user/guide/img/settings-7.png
  docs/user/guide/img/settings-8.png
  docs/user/guide/img/settings-9.png
  docs/user/guide/img/settings-cplus-tab.png
  docs/user/guide/img/settings-qgis.png
  docs/user/guide/img/step2-im-disabled.png
  docs/user/guide/img/step3-pwl-disabled.png
  docs/user/guide/img/step4-1.png
  docs/user/guide/logs.md
  docs/user/guide/settings.md
  docs/user/guide/step-2.md
  docs/user/guide/step-3.md
  docs/user/guide/step-4.md
  docs/user/manual/settings.md
Labels: documentation, Size: 13
